sudo: required
services:
  - docker

before_install: 
  - docker build -t dhavalpandya132/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dhavalpandya132/docker-react npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-test"
  env: "Docker-test-env"
  bucket_name: "elasticbeanstalk-us-east-1-886640936384"
  bucket_path: "Docker-test-env"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET